name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          
      - name: Zip Lambda function
        run: |
          zip -r lambda.zip index.js
        working-directory: ${{ github.workspace }} 
      - name: Deploy to Lambda
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws lambda update-function-code --function-name github-function --zip-file fileb://lambda.zip
        env:
          AWS_ACCESS_KEY_ID: AKIAVI2K6HJKUSEA3ZEV #${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: 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 #${{ secrets.AWS_SECRET_ACCESS_KEY }}
